problem: should use RPC to set chain params for emerald
solution: use RpcApi.routeIsEmerald to set 'additional' chain params

results:

App threw an error during load
Error: Cannot find module 'store/store'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/ia/dev/etc/emerald-wallet/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ia/dev/etc/emerald-wallet/src/lib/rpcApi.js:4:1)
    at Object.<anonymous> (/Users/ia/dev/etc/emerald-wallet/src/lib/rpcApi.js:113:3)
    at Module._compile (module.js:571:32)
    at loader (/Users/ia/dev/etc/emerald-wallet/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ia/dev/etc/emerald-wallet/node_modules/babel-register/lib/node.js:154:7)
^C